# Generated by Django 6.0.6 on 2026-07-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_90f4cc_idx',
            old_name='notifications_notification_user_read_created_idx',
        ),
    ]
