# Generated by Django 6.0.6 on 2026-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notificationdelivery_recipient_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_timeout_minutes', models.PositiveIntegerField(default=5)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalate_to_secondary_guardian', models.BooleanField(default=True)),
                ('escalate_to_emergency_contacts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escalation Configuration',
                'verbose_name_plural': 'Escalation Configurations',
            },
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
