# Generated by Django 6.0.6 on 2026-07-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_escalationconfiguration_and_more'),
        ('sos', '0011_sos_escalation_level_sos_guardian_response_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_level', models.CharField(choices=[('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('EMERGENCY_CONTACT', 'Emergency Contact')], max_length=30)),
                ('recipient_contact', models.CharField(blank=True, default='', max_length=255)),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('response_timeout_minutes', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_logs', to=settings.AUTH_USER_MODEL)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='sos.sos')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['sos', 'status', 'timestamp'], name='notificatio_sos_id_76f17a_idx'), models.Index(fields=['escalation_level', 'status', 'timestamp'], name='notificatio_escalat_dc4c25_idx')],
            },
        ),
    ]
