# Generated by Django 6.0.6 on 2026-07-27 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_escalationlog'),
        ('sos', '0011_sos_escalation_level_sos_guardian_response_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityBroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=30)),
                ('delivery_channel', models.CharField(blank=True, default='', max_length=30)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='QUEUED', max_length=20)),
                ('recipient_contact', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_broadcast_logs', to=settings.AUTH_USER_MODEL)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_broadcast_logs', to='sos.sos')),
            ],
            options={
                'ordering': ['-queued_at', '-id'],
                'indexes': [models.Index(fields=['sos', 'delivery_status', 'queued_at'], name='notificatio_sos_id_a14fe9_idx')],
            },
        ),
    ]
