# Generated by Django 6.0.6 on 2026-07-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_communitybroadcastlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('Push', 'Push'), ('SMS', 'SMS'), ('Email', 'Email')], default='Email', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
