# Generated by Django 6.0.6 on 2026-07-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
