# Generated by Django 6.0.6 on 2026-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0002_sos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
