# Generated by Django 6.0.6 on 2026-07-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_sos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=20),
        ),
    ]
