# Generated by Django 6.0.6 on 2026-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0004_alter_sos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sos',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
