# Generated by Django 6.0.6 on 2026-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0005_sos_latitude_sos_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sos',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sos',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sos',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
