# Generated by Django 6.0.6 on 2026-07-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0007_sosmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=20),
        ),
    ]
