# Generated by Django 6.0.6 on 2026-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0010_merge_0003_sosmessage_audio_file_0009_sosmessage_transcript_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='escalation_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sos',
            name='guardian_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
