# Generated by Django 6.0.6 on 2026-07-28 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0011_sos_escalation_level_sos_guardian_response_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIGGERED', 'Triggered'), ('GUARDIAN_NOTIFIED', 'Guardian Notified'), ('GUARDIAN_RESPONDED', 'Guardian Responded'), ('AUTO_ESCALATED', 'Auto Escalated'), ('VOLUNTEER_NOTIFIED', 'Volunteer Notified'), ('VOLUNTEER_ACCEPTED', 'Volunteer Accepted'), ('SECURITY_NOTIFIED', 'Security Notified'), ('SECURITY_RESPONDED', 'Security Responded'), ('INCIDENT_CLOSED', 'Incident Closed')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='sos.sos')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
            },
        ),
    ]
