# Generated by Django 6.0.6 on 2026-08-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0013_sos_assigned_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
