# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sos", "0014_alter_sos_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sos",
            name="closure_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sos",
            name="resolution_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sos",
            name="actions_taken",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sos",
            name="additional_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sos",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
