# Generated by Django 6.0.6 on 2026-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='total_flats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
