# Generated by Django 6.0.6 on 2026-07-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_block_total_flats'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.CharField(default='2 BHK', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
    ]
