# Generated by Django 6.0.6 on 2026-07-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_flat_flat_type_alter_flat_floor'),
        ('users', '0003_guardianprofile_securityprofile_volunteerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentprofile',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='residentprofile',
            name='floor',
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='society.flat'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='society.society'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='society.block'),
        ),
    ]
