# Generated by Django 6.0.6 on 2026-07-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_residentprofile_flat_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=50)),
                ('contact_type', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='users.residentprofile')),
            ],
        ),
    ]
