# Generated by Django 6.0.6 on 2026-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emergencycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='contact_type',
            field=models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('EMERGENCY_CONTACT', 'Emergency Contact')], default='EMERGENCY_CONTACT', max_length=25),
        ),
    ]
