# Generated by Django 6.0.6 on 2026-07-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emergencycontact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('GUARDIAN', 'Guardian'), ('VOLUNTEER', 'Volunteer'), ('SECURITY', 'Security'), ('ADMIN', 'Admin')], default='RESIDENT', max_length=20),
        ),
    ]
