# Generated by Django 6.0.6 on 2026-07-17 04:17

from django.db import migrations


def fix_empty_roles(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(role='').update(role='RESIDENT')


def reverse_fix(apps, schema_editor):
    # No need to reverse, as this is a data fix
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(fix_empty_roles, reverse_fix),
    ]
