# Generated by Django 6.0.6 on 2026-07-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_known_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_known_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
