# Generated by Django 6.0.6 on 2026-07-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0003_flat_flat_type_alter_flat_floor'),
        ('users', '0010_volunteerprofile_availability_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_staff', to='society.society'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='society.society'),
        ),
    ]
