# Generated by Django 6.0.6 on 2026-07-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_securityprofile_society_volunteerprofile_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofile',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityprofile',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
